config/routes.rb
Rails.application.routes.draw do
  # NHO: reminder to remove unused / commented out code!

  # get 'memberships/new'
  #
  # get 'memberships/create'
  #
  # get 'users/index'
  # get '/users/sign_out'
  # root to: 'teams#index'

  devise_for :users
  root to: 'teams#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  resources :users, only: [:index] # NHO: is this line being used?

  # NHO: this is fine, but feel like these routes belong nested under team
  # for easy access to which team a user is joining...
  resources :memberships, only: [:new, :create]


  resources :teams do
    resources :shows do
      resources :notes
      resources :beats do
        # NHO: looks like this is nested 4 layers deep, in that case it might help to seperate out
        # into seperate resource routes
        resources :notes
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beat.rb
class Beat < ApplicationRecord
  belongs_to :show
  has_many :notes, dependent: :destroy
  # , dependent: :destroy
end
  

app/models/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/note.rb
class Note < ApplicationRecord
  # NHO: since you want to reuse this model in different contexts, I would recommend
  # looking into polymorphic relationships to provide a more consistent / helpful
  # interface to relating any model that you want to add notes to...
  
  belongs_to :beat
  belongs_to :user
  # NHO: missing belongs_to :show ?
end

app/models/show.rb
class Show < ApplicationRecord
  # NHO: missing has_many :notes?
  has_many :beats, dependent: :destroy
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :shows, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/beats_controller.rb
class BeatsController < ApplicationController
  # NHO: can you see a line this is repetitive in this controller?
  # We can help DRY up this controller by using before_action methods to do common tasks such as
  # find a team, show
  def index
    @beat = Beat.all
  end

  def show
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.find(params[:id])
  end

  def new
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.new
  end

  def create
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat =@show.beats.create!(beat_params)
    redirect_to team_show_path(@team, @show)
  end

  def edit
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.find(params[:id])
  end

  def update
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.find(params[:id])
    @beat.update!(beat_params)
    redirect_to team_show_path(@team, @show)
  end

  def destroy
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat= Beat.find(params[:id])
    @beat.destroy
    redirect_to team_show_path(@team, @show)
  end

end

private
def beat_params
  params.require(:beat).permit(:title, :body)
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def new
    @membership = Membership.new
    @users = User.all
    @teams = Team.all
  end

  def create
    @membership = Membership.create!(membership_params)
    redirect_to teams_path
  end

  private
  def membership_params
    params.require(:membership).permit(:user_id, :team_id)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # NHO: can you see a line this is repetitive in this controller?
  # We can help DRY up this controller by using before_action methods to do common tasks such as
  # find a team, show, beat

  def show
    @note = Note.find(params[:id])
  end

  def new
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.find(params[:beat_id])
    @note = Note.new
  end

  def create
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.find(params[:beat_id])
    @beat.notes.create!(note_params.merge(user: current_user))
    redirect_to team_show_beat_path(@team, @show,@beat)
  end

  def edit
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.find(params[:beat_id])
    @note = Note.find(params[:id])
  end

  def update
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @beat = Beat.find(params[:beat_id])
    @note = Note.find(params[:id])
    @note.update(note_params)
    redirect_to team_show_beat_path(@team, @show, @beat)
  end

  def destroy
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:show_id])
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to team_show_path(@team, @show)
  end

  private
  def note_params
    params.require(:note).permit(:body, :private)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @team = Team.find(params[:team_id])
    @shows = Show.all
  end

  def show
    @team = Team.find(params[:team_id])
    @show =Show.find(params[:id])
    @beat =Beat.where(:show_id => @show.id)
    @note = Note.where(:beat_id => @beat.ids)
  end

  def edit
    @team = Team.find(params[:team_id])
    @show =Show.find(params[:id])
  end

  def update
    @team = Team.find(params[:team_id])
    @show =Show.find(params[:id])
    @show.update!(show_params.merge(team: @team))
    redirect_to team_show_path(@team, @show)
  end

  def new
    @show = Show.new
    @team = Team.find(params[:team_id])
  end

  def create
    @team = Team.find(params[:team_id])
    @show =Show.create!(show_params.merge(team: @team))
    redirect_to team_shows_path(@team, @show)
  end

  def destroy
    @team = Team.find(params[:team_id])
    @show = Show.find(params[:id])
    @show.destroy
    redirect_to team_shows_path(@team)
  end


  private
  def show_params
    params.require(:show).permit(:title, :date, :length, :body)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team =Team.find(params[:id])
    @membership =Membership.where(:team_id => @team.id)
    @shows = Show.where(:team_id => @team.id)
  end

  def new
    @team = Team.new
  end

  def create
    @team =Team.create!(team_params)
    redirect_to teams_path
  end

  def edit
    @team =Team.find(params[:id])
  end

  def update
    @team.update!(team_params)
    redirect_to teams_path
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to teams_path
  end


  private
  def team_params
    params.require(:team).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beats_helper.rb
module BeatsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beats/_form.html.erb
<%= form_for [@team,@show,@beat] do |b|%>
<div class = "inputForm">
  <div><%=b.label :Title%>
  <%=b.text_field :title%></div>
  <%=b.label :Body %>
  <%=b.text_field :body, :class => "inputBox"%>
  <div class = "submitBox"><%= b.submit "End Beat" %></div>
  </div>
<% end %>

app/views/beats/edit.html.erb
<h1>Beats</h1>
<%= render "form" %>

<div class = "navLink"><%= link_to "Back to Show", team_show_path(@team, @show) %></div>

<%= form_for [@team, @show,@beat], method: :delete, data: {confirm: "Are you sure?"} do |s|%>
  <%= s.submit "Delete beat" %>
<% end %>

app/views/beats/index.html.erb
<h1>Beats</h1>

app/views/beats/new.html.erb
<div class = "longList">
<h1>New Beat</h1>

<div><%= render "form" %></div>

<div class = "navLink"><%= link_to "Back to Show", team_show_path(@team, @show) %></div>
</div>

app/views/beats/show.html.erb
<!-- NHO: careful of you view code indendation! -->
<h1><%=@beat.title %></h1>
<p><%=@beat.body %></p>

<div class = "longList">

<%@beat.notes.each do |note| %>
<%  if note.private == true %>

  <% if current_user.id == note.user.id%>
  <div class = "noteBody"><%= note.body %>
  <li>
  <!-- NHO: recommend looking into rails helper method: time_ago_in_words for displaying human readable times  -->
  <div id = "noteID">Posted by:<%=note.user.email%> on <%=note.created_at%>
  <%= link_to "Edit this Note", edit_team_show_beat_note_path(@team, @show, @beat, note) %>
  <p>Only visible to you</p>
  </div>
  </li>
  </div>
    <% else%>
  <% end%>
  <%else%>
  <div class = "noteBody"><%= note.body %>
  <li>
  <div id = "noteID">Posted by:<%=note.user.email%> on <%=note.created_at%>
  <%= link_to "Edit this Note", edit_team_show_beat_note_path(@team, @show, @beat, note) %>
  </div>
  </li>
  </div>

<%end%>
<%end%>

</div>


<div class="bottomNav">
<div><%= link_to "Add note", new_team_show_beat_note_path(@team, @show,@beat,@path) %></div>

<div><%= link_to "Edit this Beat", edit_team_show_beat_path(@team, @show , @beat) %></div>

<div class = "navLink"><%= link_to "Back to Show", team_show_path(@team, @show) %></div>
</div>

app/views/memberships/create.html.erb
<h1>Memberships#create</h1>

<%= form_for [@team, @show] do |s|%>
  <%=s.label :Title%>
  <%=s.text_field :title%>
  <%=s.label :Date %>
  <%=s.text_field :date%>


  <p>
  <%= f.label :prospect %><br />
  <%= f.collection_select :prospect_id, @myprospects, :id, :name, :prompt => "Select a prospect" %>
  </p>

app/views/memberships/new.html.erb
<h1>New Membership</h1>
<%= form_for @membership do |s|%>
  <%=s.label :Player%>
  <%=s.collection_select :user_id, @users, :id, :email%>
  <%=s.label :Select_Team %>
  <%=s.collection_select :team_id, @teams, :id, :name%>
  <%=s.submit "Create membership" %>
<% end %>

app/views/notes/_form.html.erb
<%= form_for [@team, @show,@beat,@note] do |b|%>
<div class = "inputForm"
  <div class = "inputLabel"><%=b.label :Body%></div>

  <div><%=b.text_field :body, :class => "inputBox"%></div>

  <div class = "inputField"><%=b.label :Private? %>
  <%=b.check_box(:private)%></div>

<div class = "submitBox">  <%=b.submit "Submit" %> </div>

</div>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit note for<%= @beat.title %></h1>

<%= render "form" %>


<%= form_for [@team, @show, @beat, @note], method: :delete, data: {confirm: "Are you sure?"} do |n|%>
  <%= n.submit "Delete note" %>
<% end %>

<div class = "bottomNav">

  <div><%= link_to "Back to Show", team_show_beat_path(@team, @show, @beat) %></div>

  <div><%= form_for [@team, @show, @beat, @note], method: :delete, data: {confirm: "Are you sure?"} do |n|%>
    <%= n.submit "Delete note" %>
  <% end %></div>

</div>

app/views/notes/index.html.erb
<h1>Notes#index</h1>
<p>Find me in app/views/notes/index.html.erb</p>

<!-- NHO: reminder delete unused files generated by scaffolds!  -->

app/views/notes/new.html.erb
<div class = "longList">
<h1>New note for <%= @beat.title %></h1>
<div><%= render "form" %></div>
<div class = "bottomNav"><%= link_to "Back to Show", team_show_beat_path(@team, @show, @beat) %></div>
</div>

app/views/notes/show.html.erb
<h1>Note for <%= @beat %></h1>


<%= link_to "Edit Note", edit_show_beat_note_path %>

app/views/shows/_form.html.erb
<%= form_for [@team, @show] do |s|%>
  <%=s.label :Title%>
  <%=s.text_field :title%>
  <%=s.label :Date %>
  <%=s.text_field :date%>
  <%=s.label :Length %>
  <%=s.text_field :length%>
  <%=s.label "Hot take"%>
  <%=s.text_field :body%>
  <%= s.submit "Create/Update Show" %>
<% end %>

app/views/shows/edit.html.erb
<h1><%= @show.title %></h1>
<%= render "form"%>


<%= form_for [@team, @show], method: :delete, data: {confirm: "Are you sure?"} do |s|%>
  <%= s.submit "Delete show" %>
<% end %>

<div class = "navLink"><%= link_to "Back", team_show_path(@team, @show) %></div>

app/views/shows/index.html.erb
<h1>All Shows for <%= @team.name %></h1>

<div class = "longList">
<% @shows.each do |s| %>

<div>
<%=link_to "#{s.title}", team_show_path(@team, s)%><div class = "date"><%= s.date.strftime("%m/%d/%Y") %></div>
</div>
<% end %>
</div>

<div class="bottomNav">
<div class = "newLink"><%= link_to "New Show", new_team_show_path %></div>

<div class = "navLink"><%= link_to "Back to Teams", teams_path %></div>
</div>

<!-- link_to "#{s.title}", team_show_path(@team, s)%><div class = "date">< s.title</div> -->

app/views/shows/new.html.erb
<h2>New Show </h2>
<%= render "form" %>

<div class = "navLink"><%= link_to "Back to All Shows", team_shows_path %></div>

app/views/shows/show.html.erb
<h1><%=@show.date.strftime("%m/%d/%Y")%></h1>
<h2>"<%= @show.title %>"</h2>
<p>Run Time: <%=@show.length%> minutes</p>
<p>Hot Take: <%=@show.body%></p>

<div class = "longList">
  <h2> Beats </h2>
<%@beat.each do |beat| %>

<div>
  <p class = "listTitle"><h2><%=link_to "#{beat.title}", team_show_beat_path(@team, @show,beat)%></h2></p>

  <p class = "listBody"><%=beat.body%></p>

</div>

<%end%>
</div>

<div class="bottomNav">
  <div><%= link_to "Add Beat", new_team_show_beat_path(@team, @show) %></div>

  <div><%= link_to "Edit show", edit_team_show_path(@team, @show) %></div>

  <div class = "navLink"><%= link_to "Back to All Shows", team_shows_path %></div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |u| %>
  <%= link_to "#{u.email}", new_membership_path %>
<% end %>